development:
  sessions:
    default:
      database: elasticsearch-simple_dev
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: elasticsearch-simple_test
      hosts:
        - localhost:27017